model_class: "MEGAN"
search_algorithm: "mcts"
search_targets_file: "/home/tatzber/syntheseus_benchmark/results_6_runs/targets_top100clust.smi"
results_dir: "/home/tatzber/syntheseus_benchmark/results_6_runs/MEGAN_mcts/"
time_limit_s: 180
num_top_results: 1
inventory_smiles_file: "/home/tatzber/syntheseus_benchmark/enamine_sep_lpdc_blocks.smi" 
save_graph: False